{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "4yehegd87o5bn"
  },
  "info": {
    "title": "Steelco Monitoring",
    "version": "1.0",
    "description": "API to monitor injuries in Steelco factories",
    "contact": {
      "name": "martin meneghetti",
      "url": "martin-meneghetti.web.app",
      "email": "martin.meneghetti@barsanti.edu.it"
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000",
      "description": "Development"
    }
  ],
  "paths": {
    "/api/factory": {
      "get": {
        "summary": "Get factories",
        "operationId": "get-api-factory",
        "description": "Get all available factories",
        "tags": [
          "Factory"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Factory"
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": [
                      {
                        "id": 0,
                        "name": "Sede",
                        "address": "Via Del Lavoro 10",
                        "createdAt": "2019-08-24",
                        "updatedAt": "2019-08-24"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create factory",
        "operationId": "post-api-factory",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "security": [
          {
            "access token": []
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/CreateFactory"
        },
        "parameters": [],
        "tags": [
          "Factory"
        ],
        "description": "Create a new factory"
      }
    },
    "/api/factory/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "id",
          "in": "path",
          "required": true,
          "description": "factory id"
        }
      ],
      "get": {
        "summary": "Get factory with its injury count",
        "tags": [
          "Factory"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/FactoryById"
          }
        },
        "operationId": "get-api-factory-id",
        "description": "Get a factory by its id. Additional props like injuries count are added to the response"
      },
      "put": {
        "summary": "Update factory",
        "operationId": "put-api-factory-id",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "requestBody": {
          "$ref": "#/components/requestBodies/UpdateFactory"
        },
        "tags": [
          "Factory"
        ],
        "description": "Edit a factory using its id",
        "security": [
          {
            "access token": []
          }
        ]
      },
      "delete": {
        "summary": "Delete factory",
        "operationId": "delete-api-factory-id",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "tags": [
          "Factory"
        ],
        "description": "Delete a factory by its id",
        "security": [
          {
            "access token": []
          }
        ]
      }
    },
    "/api/injury": {
      "get": {
        "summary": "Get injuries and filter them by factory or year",
        "tags": [
          "Injury"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Injury"
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": [
                      {
                        "id": 15,
                        "date": "1995-06-10T00:00:00.000Z",
                        "description": "Arm dislocation",
                        "factoryId": 2,
                        "createdAt": "2023-03-23T09:01:46.920Z",
                        "updatedAt": "2023-03-23T09:00:07.642Z"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-injury",
        "parameters": [
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "factoryId",
            "description": "filter by factory"
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "year",
            "description": "filter by year"
          }
        ],
        "description": "Search injuries by factory or by year"
      },
      "post": {
        "summary": "Create injury record",
        "operationId": "post-api-injury",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "tags": [
          "Injury"
        ],
        "security": [
          {
            "access token": []
          }
        ],
        "description": "Create a new injury",
        "requestBody": {
          "$ref": "#/components/requestBodies/CreateInjury"
        }
      }
    },
    "/api/injury/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "id",
          "in": "path",
          "required": true,
          "description": "injury id"
        }
      ],
      "get": {
        "summary": "Get injury by id",
        "tags": [
          "Injury"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/InjuryById"
          }
        },
        "operationId": "get-api-injury-id",
        "description": ""
      },
      "put": {
        "summary": "Update injury data",
        "operationId": "put-api-injury-id",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "security": [
          {
            "access token": []
          }
        ],
        "tags": [
          "Injury"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/UpdateInjury"
        }
      },
      "delete": {
        "summary": "Delete injury",
        "operationId": "delete-api-injury-id",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "security": [
          {
            "access token": []
          }
        ],
        "tags": [
          "Injury"
        ]
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login with username and password",
        "operationId": "post-auth-login",
        "responses": {
          "200": {
            "$ref": "#/components/responses/LoginSuccessful"
          }
        },
        "description": "Login and get an access token (in the response) and a refresh token (in the http-only cookies)",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Login"
        }
      }
    },
    "/auth/user": {
      "get": {
        "summary": "Get user related to the access token",
        "tags": [
          "Auth"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "username": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "message": "Accesso consentito",
                      "user": {
                        "id": 1,
                        "username": "martin"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-auth-user",
        "description": "",
        "security": [
          {
            "access token": []
          }
        ]
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout and remove auth cookies",
        "operationId": "post-auth-logout",
        "responses": {
          "200": {
            "$ref": "#/components/responses/Success"
          }
        },
        "tags": [
          "Auth"
        ],
        "description": "remove the refresh cookie if present"
      }
    },
    "/auth/refresh": {
      "post": {
        "summary": "Get new access token",
        "operationId": "post-auth-refresh",
        "responses": {
          "200": {
            "$ref": "#/components/responses/RefreshSuccess"
          }
        },
        "tags": [
          "Auth"
        ],
        "description": "To get a new access token is required to have a valid refresh token in the cookies",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "accessToken": {
                    "type": "string"
                  }
                },
                "required": [
                  "accessToken"
                ]
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "accessToken": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/report": {
      "get": {
        "summary": "Get a general overview of injuries in Steelco",
        "tags": [
          "Report"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/GeneralReport"
          }
        },
        "operationId": "get-report",
        "description": "Get list of factories with the last injury date"
      },
      "parameters": []
    },
    "/api/report/{factoryId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "factoryId",
          "in": "path",
          "required": true,
          "description": "factory id"
        }
      ],
      "get": {
        "summary": "Get history of injuries for the provided factory",
        "tags": [
          "Report"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/FactoryHistory"
          }
        },
        "operationId": "get-report-factoryId",
        "parameters": [
          {
            "schema": {
              "type": "integer"
            },
            "in": "query",
            "name": "year",
            "description": "filter by year"
          }
        ],
        "description": "Get monthly history of injuries"
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "x-examples": {
          "Example 1": {
            "id": 0,
            "username": "martin",
            "password": "password (campo privato)",
            "createdAt": "2019-08-24",
            "updatedAt": "2019-08-24"
          }
        },
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given user."
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          },
          "updatedAt": {
            "type": "string",
            "format": "date"
          }
        }
      },
      "Factory": {
        "title": "Factory",
        "x-stoplight": {
          "id": "mn6agam3pd6dl"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date"
          },
          "updatedAt": {
            "type": "string",
            "format": "date"
          }
        },
        "x-examples": {
          "Example 1": {
            "id": 0,
            "name": "Sede",
            "address": "Via Del Lavoro 10",
            "createdAt": "2019-08-24",
            "updatedAt": "2019-08-24"
          }
        }
      },
      "Injury": {
        "type": "object",
        "x-examples": {
          "Example 1": {
            "id": 12,
            "date": "2023-03-06T23:00:00.000Z",
            "description": "Trauma Cranico",
            "factoryId": 2,
            "createdAt": "2023-03-23T08:50:40.777Z",
            "updatedAt": "2023-03-31T10:51:42.826Z"
          }
        },
        "properties": {
          "id": {
            "type": "integer"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "description": {
            "type": "string"
          },
          "factoryId": {
            "type": "integer"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    },
    "securitySchemes": {
      "access token": {
        "type": "http",
        "scheme": "bearer",
        "description": ""
      }
    },
    "requestBodies": {
      "CreateFactory": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "address",
                "name"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "address": "Via del Lavoro 10",
                  "name": "Sede"
                }
              }
            }
          }
        }
      },
      "UpdateFactory": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "address": "Via del Lavoro 10",
                  "name": "Sede"
                }
              }
            }
          }
        }
      },
      "CreateInjury": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "string",
                  "format": "date-time"
                },
                "description": {
                  "type": "string"
                },
                "factoryId": {
                  "type": "integer"
                }
              },
              "required": [
                "date",
                "description",
                "factoryId"
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "date": "2019-08-24T14:15:22Z",
                  "description": "Nuovo infortunio",
                  "factoryId": 4
                }
              }
            }
          }
        }
      },
      "UpdateInjury": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "date": {
                  "type": "string",
                  "format": "date-time"
                },
                "description": {
                  "type": "string"
                },
                "factoryId": {
                  "type": "integer"
                }
              }
            }
          }
        }
      },
      "Login": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "username": "martin",
                  "password": "password"
                }
              }
            }
          }
        }
      }
    },
    "responses": {
      "Success": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "message": "Operazione avvenuta con successo"
                }
              }
            }
          }
        }
      },
      "FactoryById": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/Factory"
                },
                {
                  "type": "object",
                  "properties": {
                    "_count": {
                      "type": "object",
                      "properties": {
                        "injuries": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "Example 1": {
                "value": {
                  "id": 0,
                  "name": "Sede",
                  "address": "Via del lavoro",
                  "createdAt": "2019-08-24",
                  "updatedAt": "2019-08-24",
                  "_count": {
                    "injuries": 0
                  }
                }
              }
            }
          }
        }
      },
      "500Error": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "message": "Si è verificato un errore. Riprova piu tardi"
                }
              }
            }
          },
          "application/xml": {
            "schema": {
              "type": "object",
              "properties": {}
            }
          },
          "multipart/form-data": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "InjuryById": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Injury"
            },
            "examples": {
              "Example 1": {
                "value": {
                  "id": 15,
                  "date": "1995-06-10T00:00:00.000Z",
                  "description": "Arm dislocation",
                  "factoryId": 2,
                  "createdAt": "2023-03-23T09:01:46.920Z",
                  "updatedAt": "2023-03-23T09:00:07.642Z"
                }
              }
            }
          },
          "application/xml": {
            "schema": {
              "type": "object",
              "properties": {}
            }
          },
          "multipart/form-data": {
            "schema": {
              "$ref": "#/components/schemas/Injury"
            }
          }
        }
      },
      "404Error": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "message": "Elemento non trovato"
                }
              }
            }
          }
        }
      },
      "FactoryHistory": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "x-examples": {
                "Example 1": [
                  {
                    "date": "1995-06-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2000-01-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2004-02-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2004-03-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2004-04-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2012-12-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2020-09-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2023-01-01T00:00:00.000Z",
                    "count": 2
                  },
                  {
                    "date": "2023-03-01T00:00:00.000Z",
                    "count": 1
                  },
                  {
                    "date": "2023-06-01T00:00:00.000Z",
                    "count": 1
                  }
                ]
              },
              "items": {
                "type": "object",
                "properties": {
                  "date": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "count": {
                    "type": "integer"
                  }
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": [
                  {
                    "date": "2019-08-24T14:15:22Z",
                    "count": 0
                  }
                ]
              }
            }
          }
        }
      },
      "GeneralReport": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "x-examples": {
                "Example 1": [
                  {
                    "id": 2,
                    "name": "Academy",
                    "address": "Via del Lavoro 41",
                    "lastInjuryDate": "2023-06-06T22:00:00.000Z"
                  },
                  {
                    "id": 13,
                    "name": "Centro Gestione",
                    "address": "Via PassoAlto 12",
                    "lastInjuryDate": null
                  },
                  {
                    "id": 12,
                    "name": "Fabbrica Test 3",
                    "address": "Via Quartiere 18/B",
                    "lastInjuryDate": null
                  },
                  {
                    "id": 5,
                    "name": "Officina",
                    "address": "Via del Lavoro 12",
                    "lastInjuryDate": null
                  },
                  {
                    "id": 18,
                    "name": "Pharma",
                    "address": "Via del Lavoro 10",
                    "lastInjuryDate": null
                  },
                  {
                    "id": 17,
                    "name": "Sede",
                    "address": "Via Balegante 28",
                    "lastInjuryDate": null
                  }
                ]
              },
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  },
                  "lastInjuryDate": {
                    "type": "string",
                    "format": "date-time",
                    "nullable": true
                  }
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": [
                  {
                    "id": 2,
                    "name": "Academy",
                    "address": "Via del Lavoro 41",
                    "lastInjuryDate": "2023-06-06T22:00:00.000Z"
                  }
                ]
              }
            }
          }
        }
      },
      "LoginSuccessful": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              },
              "x-examples": {
                "Example 1": {
                  "message": "Accesso consentito",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4MDM1ODY4MCwiZXhwIjoxNjgwMzU5NTgwfQ.oCWOUBkW-uSHsNVw9XF8n1um2g0gv3JvklmW989GY8I"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "message": "Accesso consentito",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4MDM1ODY4MCwiZXhwIjoxNjgwMzU5NTgwfQ.oCWOUBkW-uSHsNVw9XF8n1um2g0gv3JvklmW989GY8I"
                }
              }
            }
          }
        }
      },
      "RefreshSuccess": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "accessToken": {
                  "type": "string"
                }
              },
              "x-examples": {
                "Example 1": {
                  "message": "Accesso consentito",
                  "accessToken": "some"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "message": "Accesso consentito",
                  "accessToken": "someToken"
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Auth"
    },
    {
      "name": "Factory"
    },
    {
      "name": "Injury"
    },
    {
      "name": "Report"
    }
  ]
}